#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 26 13:48:09 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
